project 'SaveTheShoes.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SaveTheShoes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SaveTheShoes
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => react_native_path

  target 'SaveTheShoesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SaveTheShoes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SaveTheShoes-tvOS

  target 'SaveTheShoes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
